/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.unicam.cs.ids2021;
import it.unicam.cs.ids2021.consegne.*;
import it.unicam.cs.ids2021.negozio.*;
import javafx.application.Application;
import org.apache.commons.lang3.RandomStringUtils;

import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;

public class App {
    Prodotto a = new Prodotti("1", "Pasta", 1.0, CategorieProdotti.ALIMENTARI, 1);
    Prodotto b = new Prodotti("2", "Pomodoro", 2.0, CategorieProdotti.ALIMENTARI, 1);
    Prodotto c = new Prodotti("3", "Gonna", 30.50, CategorieProdotti.VESTIARIO, 1);
    Prodotto d = new Prodotti("4", "Aspirapolvere", 138.90, CategorieProdotti.ELETTRONICA, 1);
    Prodotto e = new Prodotti("4", "Giocattoli", 138.90, CategorieProdotti.GIOCHI, 1);
    Prodotto f = new Prodotti("5", "Giocattoli", 138.90, CategorieProdotti.GIOCHI, 1);

    public Map<Prodotto, Integer> creaMappaProdotti() {
        Map<Prodotto, Integer> map = new HashMap<>();
        map.put(a, 2);
        map.put(b, 2);
        map.put(c, 2);
        map.put(d, 2);
        return map;
    }


    static Set<Negozio> setN= new HashSet<>();

    static GestoreNegozioI gN = new GestoreNegozio(setN);

//main-----------------------------------------------------------------------------------------
    public static void main(String[] args) {

        setN.add(new Negozi("Si Con Te ", Posizione.ZONA_A));
        setN.add(new Negozi("Conad", Posizione.ZONA_B));
        Set<Ordine> setOrdine= new HashSet<>();
        Ordine o = new GestoreOrdini(setOrdine).creaOrdine(new App().creaMappaProdotti());
        o.setIdOrdine("a");
        System.out.println("Codice" + o.getIdOrdine());


        Application.launch(JavaFX.class);
    }
}