/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.unicam.cs.ids2021;
import javafx.application.Application;
import org.apache.commons.lang3.RandomStringUtils;

public class App {

    public static void main(String[] args) {
        Application.launch(JavaFX.class);
    }
}